version: "2.4"
services:
  db:
    image: postgres:13.12
    ports:
      - "5432:5432"
    environment:
      PGUSER: user
      PGPASSWORD: password
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: megahertz
